require "plugins"
require "coc_setting"
require "coc_keymap"
require "fzf_keymap"
require "fzf_setting"
-- require "telescope_setting"
-- require "telescope_keymap"
require "normal_setting"
require "c_setting"
require "python_setting"
require "keymap"

